// Auto-generated by core/excel/build-browser.mjs from render-core.mjs.
// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.
// StableBlock の図の描画(SVG 文字列)。HTML 版 / VSCode 拡張 Webview の画面と書き出し(SVG / PNG / 透過PNG / PNGをコピー)が
// 同じ関数を使う。browser 版は core/excel/build-browser.mjs が render-core.browser.js を生成する(window.StableBlockRender)。
// DOM API は使用禁止 — node --test で検証する純粋関数のみ。接続の端点・線の形・ラベルの置き場所は core/label の関数を
// 引数 L で受け取る(browser 版は window.StableBlockLabel、node は label-core.mjs の名前空間)。measure はラベル文字列の幅(px)。
//
// 画面の状態(view)は描画にだけ効き、本文は変えない:
//   zoom(表示倍率)/ sel([{type,id}])/ highlight(未接続を薄く)/ search(検索語)/ showAnnotations(注釈の表示)/
//   snapGuides([{x1,y1,x2,y2}])/ grid(背景の点)/ interactive(data-resize のハンドル・cursor)/ font
// 書き出し(exportSvg)はこれらを持ち込まない: 選択・ハンドル・スナップガイド・グリッド・薄め無し、注釈は本文どおり全部、
// 大きさは @canvas の寸法(倍率 1)。同じ本文からは画面の状態に関わらずバイト一致の SVG になる。

const RD_FONT = "'IBM Plex Sans','Noto Sans JP',sans-serif";
const RD_DIM = 0.15, RD_SEARCH_DIM = 0.2;

function rdEsc(t) {
  return String(t).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function rdInside(c, p) { return c.x >= p.x && c.y >= p.y && c.x + c.w <= p.x + p.w && c.y + c.h <= p.y + p.h; }

// 検索語に当たるか(ID・表示名。接続は from / to も)。q は小文字にしてから渡す
function matchesSearchItem(item, q) {
  if (!q) return true;
  const has = v => !!v && String(v).toLowerCase().indexOf(q) >= 0;
  return has(item.id) || has(item.label) || has(item.from) || has(item.to);
}

// 検索語に当たる block / group / note を読み順(上から、同じ高さなら左から)に並べた [{type,id}]。
// 検索欄の件数と Enter / Shift+Enter の移動先(HTML 版・VSCode 拡張で共通)。注釈を隠しているとき(showAnnotations: false)は note を数えない
function searchMatches(parsed, q, opts = {}) {
  const s = q ? String(q).toLowerCase() : '';
  if (!s.trim()) return [];
  const rank = { group: 0, block: 1, note: 2 };
  const items = [
    ...(parsed.groups || []).map(it => ({ type: 'group', it })),
    ...(parsed.blocks || []).map(it => ({ type: 'block', it })),
    ...(opts.showAnnotations === false ? [] : (parsed.notes || []).map(it => ({ type: 'note', it }))),
  ].filter(({ it }) => matchesSearchItem(it, s));
  items.sort((a, b) => a.it.y - b.it.y || a.it.x - b.it.x || rank[a.type] - rank[b.type]);
  return items.map(({ type, it }) => ({ type, id: it.id }));
}

// 当たり matches の中で、今の選択 cur({type,id} か null)の次(dir = 1)/ 前(dir = -1)。端は反対側へ回る。
// cur が当たりに無ければ(ID を直して外れた・何も選んでいない)次は先頭、前は末尾。当たりが無ければ null
function nextMatch(matches, cur, dir = 1) {
  const n = (matches || []).length;
  if (!n) return null;
  const i = cur ? matches.findIndex(m => m.type === cur.type && m.id === cur.id) : -1;
  if (i < 0) return matches[dir < 0 ? n - 1 : 0];
  return matches[((i + (dir < 0 ? -1 : 1)) % n + n) % n];
}

// 注釈レイヤーの接続(note が端のもの)
function isAnnotationConnOf(parsed, c) {
  const nm = parsed.noteMap || parsed.nm || {};
  return !!(nm[c.from] || nm[c.to]);
}

// PNG の画素数: @canvas の寸法 × 固定の倍率 2(表示倍率・窓の大きさに依らない)
function exportPngSize(canvas) {
  return { width: canvas.width * 2, height: canvas.height * 2 };
}

// 接続ラベル(置き場所 LL は core/label の placeLabels / labelLayout)。block より上の層に白地で描く
function rdLabelBox(c, LL) {
  return `<rect x="${LL.bg.x}" y="${LL.bg.y}" width="${LL.bg.w}" height="${LL.bg.h}" rx="${LL.bg.rx}" fill="#FFFFFF" style="pointer-events:none"/>` +
    `<text x="${LL.tx}" y="${LL.ty}" font-size="10" fill="${c.color}" text-anchor="${LL.anchor}" dominant-baseline="central" font-weight="500" style="pointer-events:none">${rdEsc(c.label)}</text>`;
}

// 図を SVG 文字列にする。描画順: group → 通常の接続 → block → 接続ラベル → 注釈レイヤー → リサイズハンドル → スナップガイド
function renderSvg(parsed, view, L, measure) {
  const v = view || {};
  const zoom = v.zoom || 1, sel = v.sel || [], q = v.search ? String(v.search).toLowerCase() : '';
  const showAnno = v.showAnnotations !== false, interactive = v.interactive !== false;
  const font = v.font || RD_FONT;
  const { canvas, blocks, groups, notes, connections, blockMap } = parsed, g = canvas.grid;
  const noteMap = parsed.noteMap || parsed.nm || {};
  const isSel = id => sel.some(s => s.id === id);
  const grab = interactive ? ' style="cursor:grab"' : '';
  const route = c => L.connRoute(c, canvas);
  const opAttr = op => (op !== null ? ` opacity="${op}"` : '');

  let hlIds = null, hlGroups = null;
  if (v.highlight) {
    hlIds = new Set();
    connections.forEach(c => { hlIds.add(c.from); hlIds.add(c.to); });
    hlGroups = new Set();
    blocks.forEach(b => { if (hlIds.has(b.id)) groups.forEach(gr => { if (rdInside(b, gr)) hlGroups.add(gr.id); }); });
  }
  const normalConns = connections.filter(c => !isAnnotationConnOf(parsed, c));
  const annoConns = connections.filter(c => isAnnotationConnOf(parsed, c));

  let s = `<svg width="${canvas.width * zoom}" height="${canvas.height * zoom}" viewBox="0 0 ${canvas.width} ${canvas.height}" xmlns="http://www.w3.org/2000/svg" style="font-family:${font}">`;
  s += '<defs>';
  if (v.grid) s += `<pattern id="gd" width="${g}" height="${g}" patternUnits="userSpaceOnUse"><circle cx="${g / 2}" cy="${g / 2}" r="0.5" fill="#CBD5E1" opacity="0.5"/></pattern>`;
  connections.forEach((c, i) => { s += `<marker id="a${i}" viewBox="0 0 10 7" refX="9" refY="3.5" markerWidth="8" markerHeight="6" orient="auto-start-reverse"><path d="M0,0 L10,3.5 L0,7 Z" fill="${c.color}"/></marker>`; });
  s += '</defs>';
  if (v.grid) s += '<rect width="100%" height="100%" fill="url(#gd)"/>';

  // Groups
  groups.forEach(gr => {
    const sl = isSel(gr.id);
    const op = hlIds && !hlGroups.has(gr.id) ? RD_DIM : q && !matchesSearchItem(gr, q) ? RD_SEARCH_DIM : null;
    s += `<g data-type="group" data-id="${gr.id}"${grab}${opAttr(op)}>`;
    s += `<rect x="${gr.x * g}" y="${gr.y * g}" width="${gr.w * g}" height="${gr.h * g}" fill="${gr.color}" stroke="${sl ? '#6366F1' : gr.borderColor}" stroke-width="${sl ? 3 : 1.5}" rx="8" opacity="0.85"${sl ? ' stroke-dasharray="8,4"' : ''}/>`;
    s += `<text x="${gr.x * g + 8}" y="${gr.y * g + 14}" font-size="11" font-weight="600" fill="${gr.borderColor}" opacity="0.9" style="pointer-events:none">${rdEsc(gr.label)}</text></g>`;
  });

  // Normal connections
  const ports = L.computePorts(normalConns, blockMap, g);
  const labelItems = [];
  normalConns.forEach((c, i) => {
    const p = ports[i]; if (!p) return;
    const dash = c.style === 'dashed' ? ' stroke-dasharray="6,3"' : '';
    const op = hlIds && !(hlIds.has(c.from) && hlIds.has(c.to)) ? RD_DIM : q && !matchesSearchItem(c, q) ? RD_SEARCH_DIM : null;
    const ci = connections.indexOf(c);
    const pi = L.connPathInfo(p.fp, p.tp, p.fs, p.ts, route(c));
    s += `<g${opAttr(op)}>`;
    s += `<path d="${pi.d}" fill="none" stroke="${c.color}" stroke-width="${c.width}"${dash} marker-end="url(#a${ci})"${c.bidir ? ` marker-start="url(#a${ci})"` : ''}/>`;
    if (c.label) labelItems.push({ conn: c, mid: pi.mid, op });
    s += '</g>';
  });

  // Blocks
  blocks.forEach(b => {
    const sl = isSel(b.id), sw = sl ? 2.5 : b.style === 'bold' ? 2.5 : 1, dash = b.style === 'dashed' ? ' stroke-dasharray="6,3"' : '';
    const flt = sl ? 'drop-shadow(0 4px 12px rgba(99,102,241,0.5))' : 'drop-shadow(0 1px 2px rgba(0,0,0,0.12))';
    const op = hlIds && !hlIds.has(b.id) ? RD_DIM : q && !matchesSearchItem(b, q) ? RD_SEARCH_DIM : null;
    s += `<g data-type="block" data-id="${b.id}"${grab}${opAttr(op)}>`;
    s += `<rect x="${b.x * g}" y="${b.y * g}" width="${b.w * g}" height="${b.h * g}" fill="${b.color}" stroke="${sl ? '#FFFFFF' : (b.borderColor || b.color)}" stroke-width="${sw}"${dash} rx="${b.round}" style="filter:${flt}"/>`;
    b.label.split('\\n').forEach((line, li, arr) => {
      const ty = b.y * g + b.h * g / 2 + (li - (arr.length - 1) / 2) * 14;
      s += `<text x="${b.x * g + b.w * g / 2}" y="${ty}" font-size="11" font-weight="600" fill="${b.textColor}" text-anchor="middle" dominant-baseline="central" style="pointer-events:none">${rdEsc(line)}</text>`;
    });
    s += '</g>';
  });

  // 接続ラベル: block より上に描く(本文に lpos= が無いラベルは block・名前・note・他のラベルを避けた位置に置く)
  L.placeLabels(labelItems, parsed, measure).forEach(LL => {
    const op = labelItems.find(it => it.conn === LL.conn).op;
    s += `<g class="conn-label" data-from="${rdEsc(LL.conn.from)}" data-to="${rdEsc(LL.conn.to)}"${opAttr(op)}>${rdLabelBox(LL.conn, LL)}</g>`;
  });

  // 注釈レイヤー(最上層)
  if (showAnno) {
    const allItems = Object.assign({}, blockMap, noteMap);
    const annoPorts = L.computePorts(annoConns, allItems, g);
    annoConns.forEach((c, i) => {
      const p = annoPorts[i]; if (!p) return;
      const ci = connections.indexOf(c);
      const pi = L.connPathInfo(p.fp, p.tp, p.fs, p.ts, route(c));
      s += '<g>';
      s += `<path d="${pi.d}" fill="none" stroke="${c.color}" stroke-width="${c.width}" stroke-dasharray="6,3" marker-end="url(#a${ci})"${c.bidir ? ` marker-start="url(#a${ci})"` : ''}/>`;
      if (c.label) s += rdLabelBox(c, L.labelLayout(pi.mid, c.lpos, measure(c.label)));
      s += '</g>';
    });
    notes.forEach(n => {
      const sl = isSel(n.id);
      const op = q && !matchesSearchItem(n, q) ? RD_SEARCH_DIM : null;
      s += `<g data-type="note" data-id="${n.id}"${grab}${opAttr(op)}>`;
      // style= を書いていない note は注釈の破線枠。書いた note は block と同じ規則(solid = 実線、dashed = 破線、bold = 太線)
      const nd = n.style == null ? '4,2' : n.style === 'dashed' ? '6,3' : null, nw = n.style === 'bold' ? 2.5 : 1;
      s += `<rect x="${n.x * g}" y="${n.y * g}" width="${n.w * g}" height="${n.h * g}" fill="${n.color}" stroke="${sl ? '#F59E0B' : (n.borderColor || '#D97706')}" stroke-width="${sl ? 2.5 : nw}"${nd ? ` stroke-dasharray="${nd}"` : ''} rx="${n.round}" style="filter:drop-shadow(0 1px 2px rgba(0,0,0,0.08))"/>`;
      n.label.split('\\n').forEach((line, li) => {
        const ty = n.y * g + 6 + li * 14;
        s += `<text x="${n.x * g + 6}" y="${ty + 10}" font-size="11" font-weight="400" fill="${n.textColor}" text-anchor="start" style="pointer-events:none">${rdEsc(line)}</text>`;
      });
      s += '</g>';
    });
  }

  // 選択中の要素のリサイズハンドル
  if (interactive) sel.forEach(si => {
    const it = blockMap[si.id] || (parsed.groupMap || {})[si.id] || noteMap[si.id]; if (!it) return;
    const x = it.x * g, y = it.y * g, w = it.w * g, h = it.h * g, hs = 10, hitS = 20;
    const hColor = (it.type || si.type) === 'note' ? '#F59E0B' : '#6366F1';
    [
      { cx: x, cy: y, cur: 'nw-resize', edge: 'nw' }, { cx: x + w, cy: y, cur: 'ne-resize', edge: 'ne' },
      { cx: x, cy: y + h, cur: 'sw-resize', edge: 'sw' }, { cx: x + w, cy: y + h, cur: 'se-resize', edge: 'se' },
      { cx: x + w / 2, cy: y, cur: 'n-resize', edge: 'n' }, { cx: x + w / 2, cy: y + h, cur: 's-resize', edge: 's' },
      { cx: x, cy: y + h / 2, cur: 'w-resize', edge: 'w' }, { cx: x + w, cy: y + h / 2, cur: 'e-resize', edge: 'e' },
    ].forEach(hd => {
      s += `<rect data-resize="${hd.edge}" data-rid="${si.id}" data-rtype="${si.type}" x="${hd.cx - hitS / 2}" y="${hd.cy - hitS / 2}" width="${hitS}" height="${hitS}" fill="transparent" style="cursor:${hd.cur}"/>`;
      s += `<rect x="${hd.cx - hs / 2}" y="${hd.cy - hs / 2}" width="${hs}" height="${hs}" fill="${hColor}" stroke="#fff" stroke-width="1.5" rx="2" style="pointer-events:none"/>`;
    });
  });

  // スナップガイド(ドラッグ中だけ)
  if (interactive && v.snapGuides) v.snapGuides.forEach(sg => {
    s += `<line x1="${sg.x1}" y1="${sg.y1}" x2="${sg.x2}" y2="${sg.y2}" stroke="#F59E0B" stroke-width="0.5" stroke-dasharray="4,2" opacity="0.8"/>`;
  });

  return s + '</svg>';
}

// 書き出し用の SVG: 本文だけで決まる(画面の選択・ハンドル・スナップガイド・グリッド・検索や「未接続を薄く」の薄め・
// 注釈の表示切替・表示倍率を持ち込まない)。大きさは @canvas の寸法
function exportSvg(parsed, L, measure, font) {
  return renderSvg(parsed, { zoom: 1, grid: false, interactive: false, showAnnotations: true, font }, L, measure);
}

;window.StableBlockRender = { matchesSearchItem, searchMatches, nextMatch, isAnnotationConnOf, exportPngSize, renderSvg, exportSvg };
