// Build derivatives for browser file:// usage:
// - template-inline.js: window.StableBlockTemplateFiles = { ... }
// - emitter.browser.js: emitter.js with `export` stripped + window.StableBlockExcel = { ... }
//
// Usage:
//   node core/excel/build-browser.mjs
//   npm run build:browser

import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative, sep } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SKELETON_DIR = join(__dirname, 'template-skeleton');
const EMITTER_SRC = join(__dirname, 'emitter.js');
const OUT_TEMPLATE = join(__dirname, 'template-inline.js');
const OUT_EMITTER_BROWSER = join(__dirname, 'emitter.browser.js');

/**
 * Walk a directory recursively and return all files as { relativePath, content }.
 * relativePath uses forward slashes regardless of OS.
 */
function walkDir(rootDir) {
  const out = [];
  function walk(dir) {
    for (const entry of readdirSync(dir)) {
      const full = join(dir, entry);
      const s = statSync(full);
      if (s.isDirectory()) {
        walk(full);
      } else {
        const rel = relative(rootDir, full).split(sep).join('/');
        out.push({ relativePath: rel, content: readFileSync(full, 'utf8') });
      }
    }
  }
  walk(rootDir);
  out.sort((a, b) => a.relativePath.localeCompare(b.relativePath));
  return out;
}

/**
 * Build the content of template-inline.js.
 */
export function buildTemplateInline(skeletonFiles) {
  const obj = {};
  for (const f of skeletonFiles) {
    obj[f.relativePath] = f.content;
  }
  return '// Auto-generated by core/excel/build-browser.mjs from template-skeleton/.\n' +
         '// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.\n' +
         'window.StableBlockTemplateFiles = ' + JSON.stringify(obj, null, 2) + ';\n';
}

/**
 * Build the content of emitter.browser.js from emitter.js source.
 */
export function buildEmitterBrowser(emitterSource) {
  // Find all exported function names
  const exportNames = [];
  const exportRegex = /^\s*export\s+(?:async\s+)?function\s+(\w+)/gm;
  let match;
  while ((match = exportRegex.exec(emitterSource)) !== null) {
    exportNames.push(match[1]);
  }
  if (exportNames.length === 0) {
    throw new Error('build-browser: no exported functions found in emitter.js');
  }
  // Strip `export` keyword
  const stripped = emitterSource.replace(/^(\s*)export\s+(async\s+)?function\s+(\w+)/gm, '$1$2function $3');
  const trailer = '\n;window.StableBlockExcel = { ' + exportNames.join(', ') + ' };\n';
  return '// Auto-generated by core/excel/build-browser.mjs from emitter.js.\n' +
         '// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.\n' +
         stripped + trailer;
}

/**
 * CLI entry point.
 */
function main() {
  const skeletonFiles = walkDir(SKELETON_DIR);
  const emitterSource = readFileSync(EMITTER_SRC, 'utf8');
  writeFileSync(OUT_TEMPLATE, buildTemplateInline(skeletonFiles));
  writeFileSync(OUT_EMITTER_BROWSER, buildEmitterBrowser(emitterSource));
  console.log(`Wrote: ${OUT_TEMPLATE}`);
  console.log(`Wrote: ${OUT_EMITTER_BROWSER}`);
}

// Only run main when invoked as a CLI script
if (import.meta.url === `file://${process.argv[1].replace(/\\/g, '/')}` ||
    process.argv[1].endsWith('build-browser.mjs')) {
  main();
}
