// Auto-generated by core/excel/build-browser.mjs from check-core.mjs.
// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.
// StableBlock 図の検査(HTML版 / VSCode拡張 Webview / CLI 共用)。
// browser 版は core/excel/build-browser.mjs が check-core.browser.js を生成する(window.StableBlockCheck)。
// DOM API と import は使用禁止 — node --test で検証する純粋関数のみ。経路の点列は呼び出し側が
// core/label/label-core.mjs の computePorts / pathPoints で作って渡す(描画と同じ計算)。
//
// 返す診断: { line, level: 'error' | 'warn', msg }。line は parse した本文の行番号(1 始まり)。

const KEYWORDS = ['block', 'group', 'note', '@canvas', '@include'];
const BOX_FORM = { block: 'block ID "ラベル" at X,Y size WxH', group: 'group ID "ラベル" at X,Y size WxH', note: 'note ID "テキスト" at X,Y size WxH' };

function editDistance(a, b) {
  const d = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)]);
  for (let j = 1; j <= b.length; j++) d[0][j] = j;
  for (let i = 1; i <= a.length; i++) for (let j = 1; j <= b.length; j++) {
    d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
  }
  return d[a.length][b.length];
}

// 読めなかった 1 行(前後の空白を除いたもの)について、何が悪いかを言う
function explainLine(raw) {
  const s = (raw || '').trim();
  const head = s.split(/\s+/)[0] || '';
  const kw = head.toLowerCase();
  if (BOX_FORM[kw]) {
    const missing = [];
    const rest = s.slice(head.length).trim();
    if (!/^\S+/.test(rest) || /^"/.test(rest)) missing.push('ID');
    if (!/"[^"]*"/.test(s)) missing.push(kw === 'note' ? '"テキスト"(二重引用符で囲む)' : '"ラベル"(二重引用符で囲む)');
    if (!/\bat\s+[\d.]+,[\d.]+/.test(s)) missing.push('at X,Y(座標は半角数字をカンマで区切る)');
    if (!/\bsize\s+[\d.]+x[\d.]+/.test(s)) missing.push('size WxH(幅と高さを小文字の x で区切る)');
    if (head !== kw) return `「${head}」は小文字で ${kw} と書く。書式: ${BOX_FORM[kw]}`;
    if (missing.length) return `${kw} の ${missing.join('・')} が読めない。書式: ${BOX_FORM[kw]}`;
    return `${kw} の並びが書式と違う。書式: ${BOX_FORM[kw]}`;
  }
  if (/<-/.test(s)) return '逆向きの矢印「<-」は書けない。向きを入れ替えて「b -> a」と書く';
  if (/-->|->/.test(s)) {
    if (/^\S+(-->|->)|(-->|->)\S/.test(s)) return '接続は矢印の前後に空白を入れて「a -> b」と書く';
    return '接続の書式と違う。書式: 「a -> b」または「a -> b "ラベル"」';
  }
  if (/^-+>?$|^=>|=>/.test(s)) return '接続の矢印は「->」(片方向)か「-->」(双方向)';
  const near = KEYWORDS.map(k => ({ k, d: editDistance(kw, k) })).sort((a, b) => a.d - b.d)[0];
  if (kw && near.d > 0 && near.d <= 2) return `「${head}」は書式にない語。${near.k} の書き間違い?`;
  if (kw.startsWith('@')) return `「${head}」は書式にない指定。使えるのは @canvas と @include`;
  return `書式にない行(先頭の「${head}」を読めない)。block / group / note / 接続「a -> b」/ @canvas のどれかで書く`;
}

// 2 つの矩形(grid)が面積を持って重なるか
function overlapArea(a, b) {
  const w = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x);
  const h = Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y);
  return w > 0 && h > 0 ? w * h : 0;
}

// 重なっている block の組
function findOverlaps(blocks) {
  const out = [];
  for (let i = 0; i < blocks.length; i++) for (let j = i + 1; j < blocks.length; j++) {
    if (overlapArea(blocks[i], blocks[j]) > 0) out.push({ a: blocks[i], b: blocks[j] });
  }
  return out;
}

// 線分 p-q が矩形 r(px, {x,y,w,h})の内部を通るか(Liang-Barsky)
function segmentHitsRect(p, q, r) {
  const dx = q.x - p.x, dy = q.y - p.y;
  let t0 = 0, t1 = 1;
  const clip = (den, num) => {
    if (den === 0) return num >= 0;
    const t = num / den;
    if (den < 0) { if (t > t1) return false; if (t > t0) t0 = t; }
    else { if (t < t0) return false; if (t < t1) t1 = t; }
    return true;
  };
  if (!clip(-dx, p.x - r.x)) return false;
  if (!clip(dx, r.x + r.w - p.x)) return false;
  if (!clip(-dy, p.y - r.y)) return false;
  if (!clip(dy, r.y + r.h - p.y)) return false;
  return t1 - t0 > 1e-9;
}

// 接続の経路が、両端以外の block の上を通る組。paths: [{ conn, pts(px) }]、blocks: grid。inset(px)だけ内側で判定し、辺に沿う線は数えない
function findCrossings(paths, blocks, g, inset = 2) {
  const out = [];
  for (const { conn, pts } of paths) {
    if (!pts || pts.length < 2) continue;
    for (const b of blocks) {
      if (b.id === conn.from || b.id === conn.to) continue;
      const r = { x: b.x * g + inset, y: b.y * g + inset, w: b.w * g - 2 * inset, h: b.h * g - 2 * inset };
      if (r.w <= 0 || r.h <= 0) continue;
      for (let i = 0; i < pts.length - 1; i++) {
        if (segmentHitsRect(pts[i], pts[i + 1], r)) { out.push({ conn, block: b }); break; }
      }
    }
  }
  return out;
}

const connText = c => `${c.from} ${c.bidir ? '-->' : '->'} ${c.to}`;

// 図全体の診断。lines: parse した本文の行配列(無ければ parser のメッセージをそのまま使う)。paths: findCrossings と同じ形(無ければ横切りは見ない)。labelIssues: label-core の labelIssues(無ければラベルは見ない)
function checkDiagram(parsed, lines, paths, labelIssues) {
  const out = [];
  for (const e of parsed.errors || []) {
    const raw = lines && lines[e.line - 1] !== undefined ? lines[e.line - 1].trim() : null;
    const unread = raw !== null ? raw.substring(0, 40) === e.msg : !/^ID "|^@include /.test(e.msg);
    out.push({ line: e.line, level: 'error', msg: unread ? explainLine(raw !== null ? raw : e.msg) : e.msg });
  }
  const has = id => parsed.blockMap[id] || parsed.noteMap[id];
  const seen = {};
  for (const c of parsed.connections || []) {
    const missing = [c.from, c.to].filter(id => !has(id) && !parsed.groupMap[id]);
    if (missing.length) {
      out.push({ line: c.line, level: 'error', msg: `接続「${connText(c)}」: ${missing.map(id => `「${id}」`).join('と')}という ID の block / note が無い` });
      continue;
    }
    const grp = [c.from, c.to].filter(id => !has(id) && parsed.groupMap[id]);
    if (grp.length) out.push({ line: c.line, level: 'warn', msg: `接続「${connText(c)}」: ${grp.join('と')}は group。group への接続は描かれない` });
    const key = [c.from, c.to].sort().join('\u0000');
    if (seen[key]) out.push({ line: c.line, level: 'warn', msg: `接続「${connText(c)}」は L${seen[key]} と同じ組の 2 本目` });
    else seen[key] = c.line;
  }
  for (const { a, b } of findOverlaps(parsed.blocks || [])) {
    const [p, q] = a.line <= b.line ? [a, b] : [b, a];
    out.push({ line: q.line, level: 'warn', msg: `block「${q.id}」が block「${p.id}」(L${p.line})に重なっている` });
  }
  if (paths) {
    const g = parsed.canvas.grid;
    for (const { conn, block } of findCrossings(paths, parsed.blocks || [], g)) {
      out.push({ line: conn.line, level: 'warn', msg: `接続「${connText(conn)}」の線が block「${block.id}」(L${block.line})の上を横切る` });
    }
  }
  for (const { conn, kind, item } of labelIssues || []) {
    const head = `接続「${connText(conn)}」のラベル「${conn.label}」`;
    const msg = kind === 'text' ? `${head}が block「${item.id}」(L${item.line})の名前に重なる`
      : kind === 'title' ? `${head}が group「${item.id}」(L${item.line})の見出しに重なる`
      : kind === 'note' ? `${head}が note「${item.id}」(L${item.line})の下に隠れる`
      : `${head}が接続「${connText(item)}」(L${item.line})のラベルに重なる`;
    out.push({ line: conn.line, level: 'warn', msg: `${msg}(lpos= で置き場所を変えられる)` });
  }
  const rank = { error: 0, warn: 1 };
  return out.sort((x, y) => rank[x.level] - rank[y.level] || x.line - y.line);
}

;window.StableBlockCheck = { explainLine, findOverlaps, segmentHitsRect, findCrossings, checkDiagram };
