// Auto-generated by core/excel/build-browser.mjs from check-core.mjs.
// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.
// StableBlock 図の検査(HTML版 / VSCode拡張 Webview / CLI 共用)。
// browser 版は core/excel/build-browser.mjs が check-core.browser.js を生成する(window.StableBlockCheck)。
// DOM API と import は使用禁止 — node --test で検証する純粋関数のみ。経路の点列は呼び出し側が
// core/label/label-core.mjs の computePorts / pathPoints で作って渡す(描画と同じ計算)。
//
// 返す診断: { line, level: 'error' | 'warn', msg }。line は parse した本文の行番号(1 始まり)。

const KEYWORDS = ['block', 'group', 'note', '@canvas', '@include'];
const BOX_FORM = { block: 'block ID "ラベル" at X,Y size WxH', group: 'group ID "ラベル" at X,Y size WxH', note: 'note ID "テキスト" at X,Y size WxH' };

function editDistance(a, b) {
  const d = Array.from({ length: a.length + 1 }, (_, i) => [i, ...Array(b.length).fill(0)]);
  for (let j = 1; j <= b.length; j++) d[0][j] = j;
  for (let i = 1; i <= a.length; i++) for (let j = 1; j <= b.length; j++) {
    d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
  }
  return d[a.length][b.length];
}

// 読めなかった 1 行(前後の空白を除いたもの)について、何が悪いかを言う
function explainLine(raw) {
  const s = (raw || '').trim();
  const head = s.split(/\s+/)[0] || '';
  const kw = head.toLowerCase();
  if (BOX_FORM[kw]) {
    const missing = [];
    const rest = s.slice(head.length).trim();
    if (!/^\S+/.test(rest) || /^"/.test(rest)) missing.push('ID');
    if (!/"[^"]*"/.test(s)) missing.push(kw === 'note' ? '"テキスト"(二重引用符で囲む)' : '"ラベル"(二重引用符で囲む)');
    if (!/\bat\s+[\d.]+,[\d.]+/.test(s)) missing.push('at X,Y(座標は半角数字をカンマで区切る)');
    if (!/\bsize\s+[\d.]+x[\d.]+/.test(s)) missing.push('size WxH(幅と高さを小文字の x で区切る)');
    if (head !== kw) return `「${head}」は小文字で ${kw} と書く。書式: ${BOX_FORM[kw]}`;
    if (missing.length) return `${kw} の ${missing.join('・')} が読めない。書式: ${BOX_FORM[kw]}`;
    return `${kw} の並びが書式と違う。書式: ${BOX_FORM[kw]}`;
  }
  if (/<-/.test(s)) return '逆向きの矢印「<-」は書けない。向きを入れ替えて「b -> a」と書く';
  if (/-->|->/.test(s)) {
    if (/^\S+(-->|->)|(-->|->)\S/.test(s)) return '接続は矢印の前後に空白を入れて「a -> b」と書く';
    return '接続の書式と違う。書式: 「a -> b」または「a -> b "ラベル"」';
  }
  if (/^-+>?$|^=>|=>/.test(s)) return '接続の矢印は「->」(片方向)か「-->」(双方向)';
  const near = KEYWORDS.map(k => ({ k, d: editDistance(kw, k) })).sort((a, b) => a.d - b.d)[0];
  if (kw && near.d > 0 && near.d <= 2) return `「${head}」は書式にない語。${near.k} の書き間違い?`;
  if (kw.startsWith('@')) return `「${head}」は書式にない指定。使えるのは @canvas と @include`;
  return `書式にない行(先頭の「${head}」を読めない)。block / group / note / 接続「a -> b」/ @canvas のどれかで書く`;
}

// 2 つの矩形(grid)が面積を持って重なるか
function overlapArea(a, b) {
  const w = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x);
  const h = Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y);
  return w > 0 && h > 0 ? w * h : 0;
}

// 重なっている block の組
function findOverlaps(blocks) {
  const out = [];
  for (let i = 0; i < blocks.length; i++) for (let j = i + 1; j < blocks.length; j++) {
    if (overlapArea(blocks[i], blocks[j]) > 0) out.push({ a: blocks[i], b: blocks[j] });
  }
  return out;
}

// group の枠をまたぐ block / group の組(一部だけ重なり、どちらも相手の内側に無い)。group の子は座標で決まるので、
// またいだ要素はどの group に属するかが画面と本文で食い違う。group 同士の組は後に書かれた方を item にして 1 回だけ数える
function findStraddles(blocks, groups) {
  const inside = (c, p) => c.x >= p.x && c.y >= p.y && c.x + c.w <= p.x + p.w && c.y + c.h <= p.y + p.h;
  const gs = groups || [];
  const out = [];
  for (const g of gs) {
    for (const it of [...(blocks || []), ...gs]) {
      if (it === g || overlapArea(it, g) === 0 || inside(it, g) || inside(g, it)) continue;
      if (gs.includes(it) && gs.indexOf(it) < gs.indexOf(g)) continue;
      out.push({ item: it, group: g });
    }
  }
  return out;
}

// キャンバス(`@canvas` の width / height、px)の外にはみ出す block / group / note と、はみ出す量(グリッド、切り上げ)。
// 書き出し(SVG / PNG / Excel)はキャンバスの寸法で切れる。寸法を固定した図(grow=off)では GUI の操作でも起こる
function findOutside(canvas, items) {
  const g = (canvas && canvas.grid) || 20;
  const out = [];
  if (!canvas || !(canvas.width > 0) || !(canvas.height > 0)) return out;
  for (const it of items || []) {
    if (!it) continue;
    const right = Math.max(0, Math.ceil(it.x + it.w - canvas.width / g));
    const bottom = Math.max(0, Math.ceil(it.y + it.h - canvas.height / g));
    if (right || bottom) out.push({ item: it, right, bottom });
  }
  return out;
}

// 線分 p-q が矩形 r(px, {x,y,w,h})の内部を通るか(Liang-Barsky)
function segmentHitsRect(p, q, r) {
  const dx = q.x - p.x, dy = q.y - p.y;
  let t0 = 0, t1 = 1;
  const clip = (den, num) => {
    if (den === 0) return num >= 0;
    const t = num / den;
    if (den < 0) { if (t > t1) return false; if (t > t0) t0 = t; }
    else { if (t < t0) return false; if (t < t1) t1 = t; }
    return true;
  };
  if (!clip(-dx, p.x - r.x)) return false;
  if (!clip(dx, r.x + r.w - p.x)) return false;
  if (!clip(-dy, p.y - r.y)) return false;
  if (!clip(dy, r.y + r.h - p.y)) return false;
  return t1 - t0 > 1e-9;
}

// 接続の経路が、両端以外の block の上を通る組。paths: [{ conn, pts(px) }]、blocks: grid。inset(px)だけ内側で判定し、辺に沿う線は数えない
function findCrossings(paths, blocks, g, inset = 2) {
  const out = [];
  for (const { conn, pts } of paths) {
    if (!pts || pts.length < 2) continue;
    for (const b of blocks) {
      if (b.id === conn.from || b.id === conn.to) continue;
      const r = { x: b.x * g + inset, y: b.y * g + inset, w: b.w * g - 2 * inset, h: b.h * g - 2 * inset };
      if (r.w <= 0 || r.h <= 0) continue;
      for (let i = 0; i < pts.length - 1; i++) {
        if (segmentHitsRect(pts[i], pts[i + 1], r)) { out.push({ conn, block: b }); break; }
      }
    }
  }
  return out;
}

const connText = c => `${c.from} ${c.bidir ? '-->' : '->'} ${c.to}`;

// 図全体の診断。lines: parse した本文の行配列(無ければ parser のメッセージをそのまま使う)。paths: findCrossings と同じ形(無ければ横切りは見ない)。labelIssues: label-core の labelIssues(無ければラベルは見ない)。
// where: 本文の行番号 n を診断の文中でどう書くか(省略時は L{n}。@include を展開した本文では checkIncluded が元の場所で書く)
function checkDiagram(parsed, lines, paths, labelIssues, where) {
  const ref = where || (n => `L${n}`);
  const out = [];
  for (const e of parsed.errors || []) {
    const raw = lines && lines[e.line - 1] !== undefined ? lines[e.line - 1].trim() : null;
    const unread = raw !== null ? raw.substring(0, 40) === e.msg : !/^ID "|^@include /.test(e.msg);
    out.push({ line: e.line, level: 'error', msg: unread ? explainLine(raw !== null ? raw : e.msg) : e.msg });
  }
  const has = id => parsed.blockMap[id] || parsed.noteMap[id];
  const seen = {};
  for (const c of parsed.connections || []) {
    const missing = [c.from, c.to].filter(id => !has(id) && !parsed.groupMap[id]);
    if (missing.length) {
      out.push({ line: c.line, level: 'error', msg: `接続「${connText(c)}」: ${missing.map(id => `「${id}」`).join('と')}という ID の block / note が無い` });
      continue;
    }
    const grp = [c.from, c.to].filter(id => !has(id) && parsed.groupMap[id]);
    if (grp.length) out.push({ line: c.line, level: 'warn', msg: `接続「${connText(c)}」: ${grp.join('と')}は group。group への接続は描かれない` });
    const key = [c.from, c.to].sort().join('\u0000');
    if (seen[key]) out.push({ line: c.line, level: 'warn', msg: `接続「${connText(c)}」は ${ref(seen[key])} と同じ組の 2 本目` });
    else seen[key] = c.line;
  }
  for (const { a, b } of findOverlaps(parsed.blocks || [])) {
    const [p, q] = a.line <= b.line ? [a, b] : [b, a];
    out.push({ line: q.line, level: 'warn', msg: `block「${q.id}」が block「${p.id}」(${ref(p.line)})に重なっている` });
  }
  for (const { item, group } of findStraddles(parsed.blocks || [], parsed.groups || [])) {
    out.push({ line: item.line, level: 'warn', msg: `${(parsed.groups || []).includes(item) ? 'group' : 'block'}「${item.id}」が group「${group.id}」(${ref(group.line)})の枠をまたいでいる` });
  }
  if (parsed.canvas) {
    const kind = it => (parsed.groups || []).includes(it) ? 'group' : (parsed.notes || []).includes(it) ? 'note' : 'block';
    for (const { item, right, bottom } of findOutside(parsed.canvas, [...(parsed.blocks || []), ...(parsed.groups || []), ...(parsed.notes || [])])) {
      const by = [right ? `右へ ${right}` : '', bottom ? `下へ ${bottom}` : ''].filter(Boolean).join('・');
      out.push({ line: item.line, level: 'warn', msg: `${kind(item)}「${item.id}」がキャンバス(${parsed.canvas.width}×${parsed.canvas.height})の外に${by} グリッドはみ出している。書き出しでは切れる` });
    }
  }
  if (paths) {
    const g = parsed.canvas.grid;
    for (const { conn, block } of findCrossings(paths, parsed.blocks || [], g)) {
      out.push({ line: conn.line, level: 'warn', msg: `接続「${connText(conn)}」の線が block「${block.id}」(${ref(block.line)})の上を横切る` });
    }
  }
  for (const { conn, kind, item } of labelIssues || []) {
    const head = `接続「${connText(conn)}」のラベル「${conn.label}」`;
    const msg = kind === 'text' ? `${head}が block「${item.id}」(${ref(item.line)})の名前に重なる`
      : kind === 'title' ? `${head}が group「${item.id}」(${ref(item.line)})の見出しに重なる`
      : kind === 'note' ? `${head}が note「${item.id}」(${ref(item.line)})の下に隠れる`
      : `${head}が接続「${connText(item)}」(${ref(item.line)})のラベルに重なる`;
    out.push({ line: conn.line, level: 'warn', msg: `${msg}(lpos= で置き場所を変えられる)` });
  }
  const rank = { error: 0, warn: 1 };
  return out.sort((x, y) => rank[x.level] - rank[y.level] || x.line - y.line);
}

// ── @include ──────────────────────────────────────────────
// 本文と include 先はファイルのパス(区切りは /)で呼ぶ。HTML 版は「.sb 読込」で一緒に選んだファイル、VSCode 拡張は
// 拡張ホストが読んだファイル、CLI は fs から読み、同じ expandIncludes / checkIncluded を通す(同じ診断になる)。

function normPath(p) {
  const out = [];
  p.split('/').forEach((seg, i) => {
    if (seg === '.' || (seg === '' && i > 0)) return;
    const last = out[out.length - 1];
    if (seg === '..' && out.length && last !== '..' && last !== '' && !/^[a-zA-Z]:$/.test(last)) out.pop();
    else out.push(seg);
  });
  return out.join('/');
}

// include 元のファイル from(無ければ '')から見た相対パス rel を、/ 区切りのパスにする
function resolveIncludePath(from, rel) {
  const r = String(rel).split('\\').join('/');
  if (/^([a-zA-Z]:)?\//.test(r)) return normPath(r);
  const f = String(from || '').split('\\').join('/');
  return normPath(f.slice(0, f.lastIndexOf('/') + 1) + r);
}

// 本文 text の @include を展開する。read(path) は include 先の本文(読めなければ null)。file は本文のパス(相対パスの起点)。
// 返り値: text / lines(展開後)、origin[i] = { file, line, at }(展開後の i+1 行目がどのファイルの何行目か。at は本文の何行目から来たか)、
// missing = [{ at, file, line, path, resolved, cycle }](読めない @include。その行は展開後に残さない)。include の無い本文はそのまま返る。
// 画布(@canvas)は本文のものが正: 本文に @canvas があれば include 先の @canvas 行は展開しない(共有部の画布の大きさ・線の形で本文の画布を上書きしない)
function expandIncludes(text, read, file = '') {
  const lines = [], origin = [], missing = [];
  const ownCanvas = String(text).replace(/^\uFEFF/, '').split('\n').some(l => /^@canvas\b/.test(l.trim()));
  const walk = (src, f, at, chain) => {
    String(src).replace(/^\uFEFF/, '').split('\n').forEach((line, i) => {
      const top = at === undefined ? i + 1 : at;
      if (at !== undefined && ownCanvas && /^@canvas\b/.test(line.trim())) return;
      const m = line.trim().match(/^@include\s+"([^"]+)"/);
      if (m) {
        const p = resolveIncludePath(f, m[1]);
        const cycle = chain.includes(p);
        const sub = cycle ? null : read(p);
        if (sub !== null && sub !== undefined) { walk(sub, p, top, [...chain, p]); return; }
        missing.push({ at: top, file: f, line: i + 1, path: m[1], resolved: p, cycle });
        return;
      }
      lines.push(line);
      origin.push({ file: f, line: i + 1, at: top });
    });
  };
  walk(text, file, undefined, [resolveIncludePath('', file)]);
  return { text: lines.join('\n'), lines, origin, missing, file };
}

// 展開した図(parsed は exp.text を parse したもの)の診断を、本文の行番号(line)で返す。include 先の行から出た診断は
// @include 行に寄せ、どのファイルの何行目かを書き添える(file / fileLine にも持つ)。読めない @include はその行のエラーにし、
// ID が無い接続には読めていない include 先を示す。opts.hint: 読めない include に添える案内。opts.name(path): 文中のファイル名。
// opts.inline === false なら include 先の場所を文に添えない(CLI は file:line で示す)。opts.labelIssues は checkDiagram と同じ
function checkIncluded(parsed, exp, paths, opts = {}) {
  const name = opts.name || (p => p);
  const org = n => exp.origin[n - 1] || { file: exp.file, line: n, at: n };
  const where = n => { const r = org(n); return r.file === exp.file ? `L${r.line}` : `${name(r.file)} L${r.line}`; };
  const out = [];
  for (const m of exp.missing) {
    const in_ = m.file === exp.file ? '' : `(${name(m.file)} L${m.line})`;
    out.push({ line: m.at, level: 'error', msg: `include 先「${m.path}」を読めない${m.cycle ? '(自分自身を include している)' : opts.hint || ''}${in_}`, file: m.file, fileLine: m.line });
  }
  const unread = exp.missing.length ? `(読めていない include 先: ${exp.missing.map(m => `L${m.at}「${m.path}」`).join('、')})` : '';
  for (const d of checkDiagram(parsed, exp.lines, paths, opts.labelIssues, where)) {
    const r = org(d.line);
    let msg = d.msg;
    if (unread && /という ID の block \/ note が無い$/.test(msg)) msg += unread;
    if (r.file !== exp.file && opts.inline !== false) msg += `(${name(r.file)} L${r.line})`;
    out.push({ line: r.at, level: d.level, msg, file: r.file, fileLine: r.line });
  }
  const rank = { error: 0, warn: 1 };
  return out.sort((x, y) => rank[x.level] - rank[y.level] || x.line - y.line);
}

// 展開後の line 行目(parser の item.line)が include 先から来たなら { file, line, at }(本文の行なら null)
function includeOrigin(exp, line) {
  const o = exp && exp.origin && exp.origin[line - 1];
  return o && o.file !== exp.file ? { file: o.file, line: o.line, at: o.at } : null;
}

// include 先で定義された要素を選んだときの案内。この図の本文にはその行が無いので、ドラッグ・位置・大きさ・色・ラベルはここでは変わらない。
// name(path): 文中のファイル名。include 先の要素でなければ ''
function includedItemNote(exp, line, name, lang) {
  const o = includeOrigin(exp, line);
  if (!o) return '';
  const f = name ? name(o.file) : o.file;
  return lang === 'en'
    ? `Defined in the included file ${f} (line ${o.line}; @include on line ${o.at}). It cannot be moved or changed from this diagram: edit ${f}.`
    : `include 先 ${f} の L${o.line} で定義(本文 L${o.at} の @include)。この図からは動かせない・変えられないので ${f} で直す`;
}

// 書き出しの知らせに足す行: 読めない include 先の要素は書き出しにも入っていない
function includeDrops(exp) {
  return ((exp && exp.missing) || []).map(m => `include 先「${m.path}」(L${m.at})を読めず、その中の要素は入っていない`);
}

// 一緒に読み込んだ図(files: { パス: 本文 })の中から、図 self の @include 先を探す read(path)。
// パスが一致する図、無ければ self 以外で名前(最後の / の後)が 1 つだけ一致する図。どちらも無ければ null
function loadedReader(files, self) {
  const keys = Object.keys(files);
  return p => {
    if (Object.prototype.hasOwnProperty.call(files, p)) return files[p];
    const b = String(p).split('/').pop();
    const hit = keys.filter(k => k !== self && k.split('/').pop() === b);
    return hit.length === 1 ? files[hit[0]] : null;
  };
}

// 一括書き出し: 一緒に読み込んだ図を 1 枚ずつ、表示中の図と同じ探し方で @include を解決する(files の順)。
// include されるだけの図(共通部)も 1 枚として返す。返り値: [{ path, exp }](exp は expandIncludes の返り値)
function expandLoaded(files) {
  return Object.keys(files).map(path => ({ path, exp: expandIncludes(files[path], loadedReader(files, path), path) }));
}

// ─── 作図 UI から @include を足す・外す(ツール欄の「共通部(@include)」) ───

const INCLUDE_RE = /^\s*@include\s+"([^"]+)"/;

// 本文の @include 行: [{ line(1 始まり), path(書いてある文字列) }]
function includeLines(dsl) {
  const out = [];
  String(dsl).split('\n').forEach((l, i) => { const m = l.match(INCLUDE_RE); if (m) out.push({ line: i + 1, path: m[1] }); });
  return out;
}

// 図 from の本文に書いた rel が、一緒に読み込んだ図のどれか(files のキー)。loadedReader と同じ探し方。無ければ null
function loadedKeyOf(files, from, rel) {
  const p = resolveIncludePath(from, rel);
  if (Object.prototype.hasOwnProperty.call(files, p)) return p;
  const b = p.split('/').pop();
  const hit = Object.keys(files).filter(k => k !== from && k.split('/').pop() === b);
  return hit.length === 1 ? hit[0] : null;
}

// 図 k が(include 先をたどって)取り込む図のキーの集合。自分自身は入れない
function includedKeys(files, k) {
  const seen = new Set();
  const walk = f => {
    for (const { path } of includeLines(files[f])) {
      const t = loadedKeyOf(files, f, path);
      if (t && !seen.has(t) && t !== k) { seen.add(t); walk(t); }
    }
  };
  walk(k);
  return seen;
}

// from のフォルダから to への相対パス(/ 区切り)
function relativeIncludePath(from, to) {
  const a = String(from).split('/').slice(0, -1), b = String(to).split('/');
  let i = 0;
  while (i < a.length && i < b.length - 1 && a[i] === b[i]) i++;
  return [...a.slice(i).map(() => '..'), ...b.slice(i)].join('/');
}

// 図 self に @include として足せる、一緒に読み込んだ図: [{ file(キー), path(本文に書く文字列) }](ほかの図が取り込んでいる図が先、あとは files の順)。
// 自分自身・既に取り込んでいる図・自分を(include 先をたどって)取り込んでいる図は出さない(循環を作らない)。
// path は、同じフォルダのほかの図がその図を既に include している書き方があればそれ(「.sb 読込」で選んだ図はフォルダを持たないので、
// 本文どおりの `shared/common.sb` を使う)。無ければ self から見た相対パス
function includeCandidates(files, self) {
  const has = includedKeys(files, self);
  const dir = f => String(f).split('/').slice(0, -1).join('/');
  const out = [];
  for (const k of Object.keys(files)) {
    if (k === self || has.has(k) || includedKeys(files, k).has(self)) continue;
    let path = null;
    for (const f of Object.keys(files)) {
      if (f === k || dir(f) !== dir(self)) continue;
      const hit = includeLines(files[f]).find(x => loadedKeyOf(files, f, x.path) === k);
      if (hit) { path = hit.path; break; }
    }
    out.push({ file: k, path: path || relativeIncludePath(self, k) });
  }
  // 先に出す順(選ばずに押せば共通部が入る): ほかの図が既に取り込んでいる図 → 自分の接続が指していて自分に無い ID を定義している図 → 残り
  const shared = new Set(Object.keys(files).flatMap(f => includeLines(files[f]).map(x => loadedKeyOf(files, f, x.path))));
  const own = definedIds(files[self]);
  const need = new Set([...connectedIds(files[self])].filter(id => !own.has(id)));
  const rank = c => (shared.has(c.file) ? 0 : [...definedIds(files[c.file])].some(id => need.has(id)) ? 1 : 2);
  return [0, 1, 2].flatMap(r => out.filter(c => rank(c) === r));
}

// 本文(include は展開しない)で定義している ID と、接続の端に書いている ID
function definedIds(text) {
  const out = new Set();
  for (const l of String(text || '').split('\n')) { const m = l.match(/^\s*(block|group|note)\s+(\S+)/); if (m) out.add(m[2]); }
  return out;
}
function connectedIds(text) {
  const out = new Set();
  for (const l of String(text || '').split('\n')) { const m = l.match(/^\s*([^\s#@]\S*)\s+(-->|->)\s+(\S+)/); if (m) { out.add(m[1]); out.add(m[3]); } }
  return out;
}

// 本文に `@include "path"` の 1 行を足す(差分 1 行)。置き場所: 最後の @include 行の後、無ければ @canvas 行の後、
// 無ければ先頭のコメント行の後。改行コードは本文に合わせる
function addIncludeInDsl(dsl, path) {
  const s = String(dsl), cr = s.includes('\r\n') ? '\r' : '';
  const lines = s.split('\n');
  const inc = includeLines(s);
  let at;
  if (inc.length) at = inc[inc.length - 1].line;
  else {
    const c = lines.findIndex(l => /^\s*@canvas(\s|$)/.test(l));
    if (c >= 0) at = c + 1;
    else { at = 0; while (at < lines.length && /^\s*#/.test(lines[at])) at++; }
  }
  lines.splice(at, 0, `@include "${path}"` + cr);
  return lines.join('\n');
}

// 本文の line 行目(1 始まり)が @include 行ならその行を消す。そうでなければ同じ文字列
function removeIncludeInDsl(dsl, line) {
  const lines = String(dsl).split('\n');
  if (!INCLUDE_RE.test(lines[line - 1] || '')) return String(dsl);
  lines.splice(line - 1, 1);
  return lines.join('\n');
}

// 一括書き出しの zip の中のファイル名: 読み込んだ図のパスから .sb / .stableblock / .txt を除いて拡張子 ext を付ける
function bulkFileName(path, ext) {
  return String(path).replace(/\.(sb|stableblock|txt)$/i, '') + '.' + ext;
}

// 一括書き出しの知らせ: 図ごとの知らせ([{ path, dropped }])を、どの図の知らせかを頭に付けて 1 つに並べる
function bulkDrops(list) {
  return (list || []).flatMap(({ path, dropped }) => (dropped || []).map(d => `${path}: ${d}`));
}

;window.StableBlockCheck = { explainLine, findOverlaps, findStraddles, findOutside, segmentHitsRect, findCrossings, checkDiagram, resolveIncludePath, expandIncludes, checkIncluded, includeOrigin, includedItemNote, includeDrops, loadedReader, expandLoaded, includeLines, loadedKeyOf, relativeIncludePath, includeCandidates, addIncludeInDsl, removeIncludeInDsl, bulkFileName, bulkDrops };
