// Auto-generated by core/excel/build-browser.mjs from select-core.mjs.
// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.
// StableBlock のキャンバス選択の共有ロジック(HTML版 / VSCode拡張 Webview 共用)。
// browser 版は core/excel/build-browser.mjs が select-core.browser.js を生成する
// (window.StableBlockSelect)。DOM API は使用禁止 — node --test で検証する純粋関数のみ。
//
// 選択は [{type,id}] の配列。draw.io / Visio / Excel の図形と同じ規則にそろえる:
// - 押下: Shift は足す/外す。Shift なしで未選択の要素を押すと、その 1 つに置き換える。
//   選択済みの要素を押したときは、そのまま全部をドラッグできるよう選択を保つ
// - 離す: 動かさずに離した(クリック)なら、Shift なしのときは押した 1 つに置き換える
// - 本文の書換えで消えた要素は選択から落とす

function selSame(a, b) { return a.type === b.type && a.id === b.id; }
function selHas(sel, item) { return sel.some(s => selSame(s, item)); }

// mousedown で決まる選択。item = {type,id}
function pressSelect(sel, item, shift) {
  if (shift) return selHas(sel, item) ? sel.filter(s => !selSame(s, item)) : sel.concat([{ type: item.type, id: item.id }]);
  return selHas(sel, item) ? sel.slice() : [{ type: item.type, id: item.id }];
}

// mouseup で決まる選択。moved は 1 グリッド以上動いたか
function releaseSelect(sel, item, shift, moved) {
  if (shift || moved) return sel.slice();
  return selHas(sel, item) ? [{ type: item.type, id: item.id }] : sel.slice();
}

// parsed(parseDSL の結果)に無くなった要素を選択から落とす
function pruneSelection(sel, parsed) {
  if (!parsed) return sel.slice();
  const maps = { block: parsed.blockMap || {}, group: parsed.groupMap || {}, note: parsed.noteMap || {} };
  return sel.filter(s => maps[s.type] && Object.prototype.hasOwnProperty.call(maps[s.type], s.id));
}

// 2 つの選択が同じ要素の並びか(再描画の要否判定用)
function sameSelection(a, b) {
  return a.length === b.length && a.every((s, i) => selSame(s, b[i]));
}

// プロパティ欄の数値欄(X / Y / W / H)の ▲▼ が値をどれだけ変えるか。▲ は +1、▼ は -1。
// 1 つ選択でも複数選択でも同じ向き(Excel / Visio / draw.io の数値欄と同じ)。
// Y は下向きが正なので Y の ▲ は図の上では下へ動く。画面の向きで動かすのは矢印キー(arrowNudge)
function stepDelta(button) {
  return button === 'up' ? 1 : button === 'dn' ? -1 : 0;
}

// 矢印キーの移動: 画面の向きに 1 グリッド。{ axis: 'x'|'y', d: ±1 }、矢印キーでなければ null
function arrowNudge(key) {
  switch (key) {
    case 'ArrowLeft': return { axis: 'x', d: -1 };
    case 'ArrowRight': return { axis: 'x', d: 1 };
    case 'ArrowUp': return { axis: 'y', d: -1 };
    case 'ArrowDown': return { axis: 'y', d: 1 };
    default: return null;
  }
}

// ── プロパティ欄の数値・色の欄(X / Y / W / H・角丸・背景色・枠線色)の確定 ──
// 打っている間は本文に書かない(1 文字目で書くと欄が描き直され、2 文字目以降が入らない)。Enter・Tab・欄から出たときに 1 回だけ書く。
// 色は # と 6 桁が揃えば打っている間にも書く。▲▼ と欄の中の ↑↓ は今どおり 1 押しで書く(draw.io・Visio・Excel の書式欄と同じ)。

// 欄の種類: 'pos'(0 以上の整数)| 'size'(1 以上の整数)| 'round'(0 以上の整数)| 'color'(#RRGGBB)
function fieldKind(field) {
  if (field === 'x' || field === 'y') return 'pos';
  if (field === 'w' || field === 'h') return 'size';
  if (field === 'round') return 'round';
  return 'color';
}

// 欄の値 raw を本文に書くなら書く値、書かないなら null。trigger: 'input'(打っている間)| 'commit'(Enter・Tab・欄から出た)。
// current: 今の値(同じなら書かない = 取り消し履歴を増やさない)。書けない値(空・負・文字・桁の足りない色)は null
function fieldCommit(kind, raw, trigger, current) {
  const s = String(raw ?? '').trim();
  let v = null;
  if (kind === 'color') {
    if (/^#[0-9A-Fa-f]{6}$/.test(s)) v = s;
  } else if (trigger === 'commit' && /^\d+$/.test(s)) {
    const n = parseInt(s, 10);
    if (n >= (kind === 'size' ? 1 : 0)) v = n;
  }
  if (v === null) return null;
  if (current !== undefined && current !== null && String(current).toUpperCase() === String(v).toUpperCase()) return null;
  return v;
}

// 欄の中のキー: 'commit'(Enter)| 'cancel'(Esc: 打った値を捨てる)| 'up' / 'dn'(↑↓: ▲▼ と同じ)| 'next' / 'prev'(Tab / Shift+Tab)| null
function fieldKeyAction(key, shift) {
  switch (key) {
    case 'Enter': return 'commit';
    case 'Escape': return 'cancel';
    case 'ArrowUp': return 'up';
    case 'ArrowDown': return 'dn';
    case 'Tab': return shift ? 'prev' : 'next';
    default: return null;
  }
}

;window.StableBlockSelect = { pressSelect, releaseSelect, pruneSelection, sameSelection, stepDelta, arrowNudge, fieldKind, fieldCommit, fieldKeyAction };
