// Auto-generated by core/excel/build-browser.mjs from layout-core.mjs.
// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.
// StableBlock キャンバスと配置の共有ロジック(HTML版 / VSCode拡張 Webview 共用)。
// browser 版は core/excel/build-browser.mjs が layout-core.browser.js を生成する
// (window.StableBlockLayout)。DOM API は使用禁止 — node --test で検証する純粋関数のみ。
//
// 座標の単位: 要素(block / group / note)の x,y,w,h はグリッド、キャンバスの width / height は px。

// 要素の右端・下端(グリッド)。要素が無ければ 0。
function contentExtent(items) {
  let right = 0, bottom = 0;
  for (const it of items || []) {
    if (!it) continue;
    right = Math.max(right, it.x + it.w);
    bottom = Math.max(bottom, it.y + it.h);
  }
  return { right, bottom };
}

// 要素が全部収まるキャンバス寸法(px)。広げるだけで縮めない。広げるときは右・下に margin グリッドの余白を残す。
function grownCanvasSize(canvas, items, margin = 1) {
  const g = canvas.grid || 20;
  const { right, bottom } = contentExtent(items);
  let width = canvas.width, height = canvas.height;
  if (right * g > width) width = (right + margin) * g;
  if (bottom * g > height) height = (bottom + margin) * g;
  return { width, height };
}

// 書き換える `@canvas` 行(0 始まり。無ければ -1)。2 行以上あれば効くのは最後の行なので最後の行(前の行は読んだまま残す)
function canvasLineIndex(lines) {
  for (let i = lines.length - 1; i >= 0; i--) if (/^\s*@canvas(\s|$)/.test(lines[i])) return i;
  return -1;
}

// 最後の行から key= を消しても、前の `@canvas` 行に key= が残っていればそちらが効く。そのときは最後の行に既定の値を書く
function earlierCanvasHas(lines, idx, key) {
  const re = new RegExp('\\s' + key + '=\\S+');
  return lines.slice(0, idx).some(l => /^\s*@canvas(\s|$)/.test(l) && re.test(l));
}

// 本文の `@canvas` 行の width / height だけを書き換える(ほかの属性・空白・改行コードは触らない)。
// `@canvas` 行が無ければ、先頭のコメント行の直後に 1 行足す。変える必要が無ければ同じ文字列を返す。
function setCanvasInDsl(dsl, width, height) {
  const eol = dsl.includes('\r\n') ? '\r\n' : '\n';
  const lines = dsl.split('\n');
  const idx = canvasLineIndex(lines);
  if (idx < 0) {
    let at = 0;
    while (at < lines.length && /^\s*#/.test(lines[at])) at++;
    const line = `@canvas width=${width} height=${height}` + (eol === '\r\n' ? '\r' : '');
    lines.splice(at, 0, line);
    return lines.join('\n');
  }
  let line = lines[idx];
  const cr = line.endsWith('\r') ? '\r' : '';
  if (cr) line = line.slice(0, -1);
  for (const [key, val] of [['width', width], ['height', height]]) {
    const re = new RegExp(`(^|\\s)${key}=\\d+`);
    if (re.test(line)) line = line.replace(re, `$1${key}=${val}`);
    else line = line.replace(/\s*$/, '') + ` ${key}=${val}`;
  }
  lines[idx] = line + cr;
  const out = lines.join('\n');
  return out === dsl ? dsl : out;
}

// 本文の `@canvas` 行の route=(図全体の既定の線の形。route を書いていない接続に効く)だけを書き換える。
// 曲線(既定)にするときは route= を消す(何も書いていない図と同じバイトに戻る)。`@canvas` 行が無ければ、
// 先頭のコメント行の直後に `@canvas route=...` を 1 行足す。変える必要が無ければ同じ文字列を返す。
function setCanvasRouteInDsl(dsl, route) {
  const r = route === 'straight' || route === 'ortho' ? route : null;
  const eol = dsl.includes('\r\n') ? '\r\n' : '\n';
  const lines = dsl.split('\n');
  const idx = canvasLineIndex(lines);
  if (idx < 0) {
    if (!r) return dsl;
    let at = 0;
    while (at < lines.length && /^\s*#/.test(lines[at])) at++;
    lines.splice(at, 0, `@canvas route=${r}` + (eol === '\r\n' ? '\r' : ''));
    return lines.join('\n');
  }
  let line = lines[idx];
  const cr = line.endsWith('\r') ? '\r' : '';
  if (cr) line = line.slice(0, -1);
  const re = /(\s)route=\S+/;
  if (!r) {
    line = line.replace(/\s+route=\S+/, '');
    if (earlierCanvasHas(lines, idx, 'route')) line = line.replace(/\s*$/, '') + ' route=curved';
  } else if (re.test(line)) line = line.replace(re, `$1route=${r}`);
  else line = line.replace(/\s*$/, '') + ` route=${r}`;
  lines[idx] = line + cr;
  const out = lines.join('\n');
  return out === dsl ? dsl : out;
}

// 本文の `@canvas` 行の grow=off(寸法を固定し、GUI の操作ではみ出しても広げない)を書く・消す。on = true(既定)で grow= を消す。
// `@canvas` 行が無く固定にするときは、先頭のコメント行の直後に `@canvas grow=off` を 1 行足す。変える必要が無ければ同じ文字列を返す。
function setCanvasGrowInDsl(dsl, on) {
  const eol = dsl.includes('\r\n') ? '\r\n' : '\n';
  const lines = dsl.split('\n');
  const idx = canvasLineIndex(lines);
  if (idx < 0) {
    if (on) return dsl;
    let at = 0;
    while (at < lines.length && /^\s*#/.test(lines[at])) at++;
    lines.splice(at, 0, '@canvas grow=off' + (eol === '\r\n' ? '\r' : ''));
    return lines.join('\n');
  }
  let line = lines[idx];
  const cr = line.endsWith('\r') ? '\r' : '';
  if (cr) line = line.slice(0, -1);
  if (on) {
    line = line.replace(/\s+grow=\S+/, '');
    if (earlierCanvasHas(lines, idx, 'grow')) line = line.replace(/\s*$/, '') + ' grow=on';
  } else if (/\sgrow=\S+/.test(line)) line = line.replace(/(\s)grow=\S+/, '$1grow=off');
  else line = line.replace(/\s*$/, '') + ' grow=off';
  lines[idx] = line + cr;
  const out = lines.join('\n');
  return out === dsl ? dsl : out;
}

// GUI の操作でキャンバスを広げてよいか(`@canvas` 行に grow=off が無い)
function canvasGrows(canvas) {
  return !(canvas && canvas.grow === 'off');
}

// 要素がキャンバスからはみ出していれば `@canvas` 行を広げた本文を返す。はみ出していなければ、
// または寸法を固定した図(grow=off)なら同じ文字列。
function growCanvasInDsl(dsl, canvas, items, margin = 1) {
  if (!canvasGrows(canvas)) return dsl;
  const { width, height } = grownCanvasSize(canvas, items, margin);
  if (width === canvas.width && height === canvas.height) return dsl;
  return setCanvasInDsl(dsl, width, height);
}

function overlaps(a, b, gap) {
  return a.x < b.x + b.w + gap && b.x < a.x + a.w + gap && a.y < b.y + b.h + gap && b.y < a.y + a.h + gap;
}

// w x h の要素を、既存の要素と gap グリッド以上離して置ける位置を読み順(上の行から、左から)で探す。
// 横は cols(グリッド)に収まる範囲で探し、収まる所が無ければ既存の要素の下に置く。
function findFreeSlot(items, w, h, opts = {}) {
  const x0 = opts.x0 ?? 1, y0 = opts.y0 ?? 1, gap = opts.gap ?? 1;
  const list = (items || []).filter(Boolean);
  const cols = Math.max(opts.cols ?? 48, x0 + w);
  const { bottom } = contentExtent(list);
  for (let y = y0; y <= bottom + gap; y++) {
    for (let x = x0; x + w <= cols; x++) {
      const r = { x, y, w, h };
      if (!list.some(it => overlaps(r, it, gap))) return { x, y };
    }
  }
  return { x: x0, y: Math.max(y0, bottom + gap) };
}

// 「+ ブロック追加」(ツール欄・group 欄)と貼り付けの置き場所。1 つの規則で決める:
// 直前に置いたもの prev の右隣(同じ行)から読み順で、w x h を既存の要素と gap 以上離して置ける位置を探す。
// 行の右端 cols(グリッド、この値は含まない)を超えるなら次の行の x0 へ。下は足りるまで伸ばす(呼び出し側が
// キャンバスや group を広げる)。prev が無ければ領域の左上(x0, y0)から探す。
function placeNext(items, w, h, opts = {}) {
  const x0 = opts.x0 ?? 1, y0 = opts.y0 ?? 1, gap = opts.gap ?? 1, prev = opts.prev || null;
  const list = (items || []).filter(Boolean);
  const cols = Math.max(opts.cols ?? 48, x0 + w);
  const { bottom } = contentExtent(list);
  const startY = prev ? Math.max(y0, prev.y) : y0;
  const lastY = Math.max(bottom, startY) + gap;
  for (let y = startY; y <= lastY; y++) {
    const xs = prev && y === startY ? Math.max(x0, prev.x + prev.w + gap) : x0;
    for (let x = xs; x + w <= cols; x++) {
      const r = { x, y, w, h };
      if (!list.some(it => overlaps(r, it, gap))) return { x, y };
    }
  }
  return { x: x0, y: lastY };
}

// キャンバス(px)を表示欄(px)に収める倍率。max を超えて拡大しない。
function fitZoom(canvasW, canvasH, areaW, areaH, opts = {}) {
  const min = opts.min ?? 0.1, max = opts.max ?? 1;
  if (!(canvasW > 0 && canvasH > 0 && areaW > 0 && areaH > 0)) return max;
  const z = Math.min(areaW / canvasW, areaH / canvasH, max);
  return Math.max(min, Math.floor(z * 100) / 100);
}

// −/+ ボタンの次の倍率。0.25 刻みに揃える(全体表示で端数になった倍率からも刻みに戻る)。
function stepZoom(zoom, dir, opts = {}) {
  const min = opts.min ?? 0.25, max = opts.max ?? 3, step = 0.25;
  const next = dir > 0 ? Math.floor(zoom / step + 1e-9) * step + step : Math.ceil(zoom / step - 1e-9) * step - step;
  if (dir < 0) return Math.max(Math.min(min, zoom), next);
  return Math.max(min, Math.min(max, next));
}

// ── 欄の幅(HTML 版の DSL | プレビュー | ツール欄、拡張のプレビュー | サイド欄) ──
// 境界をドラッグした後の左・右の欄の幅(px、整数)。左右はそれぞれ最小幅を割らず、真ん中(プレビュー)に minMid を残す。
// 入り切らないときは動かした側(moved: 'left' | 'right')を先に削る。moved 省略(窓の大きさが変わった)は左を先に削る。
// 左の欄が無い画面は left 0・minLeft 0 で呼ぶ。
function paneWidths(total, left, right, opts = {}) {
  const minL = opts.minLeft ?? 160, minM = opts.minMid ?? 240, minR = opts.minRight ?? 200;
  let L = Math.max(minL, Math.round(Number(left) || 0));
  let R = Math.max(minR, Math.round(Number(right) || 0));
  const room = Math.max(0, Math.round(total) - minM);   // 左 + 右の上限
  if (L + R > room) {
    if (opts.moved === 'right') { R = Math.max(minR, room - L); L = Math.max(minL, room - R); }
    else { L = Math.max(minL, room - R); R = Math.max(minR, room - L); }
  }
  return { left: L, right: R };
}

// ── 入れ子の group(親 group は子を内側に収める) ──
// group の子は座標だけで決まる(子の矩形が親の矩形の内側にある)。GUI の操作(移動・大きさ変更・グループ化・group 内への追加)で
// 子が親の枠をまたいだら、枠を越えた向きに親を広げる(親の親も同じ)。本文で変わるのは広がった group の行だけ。

function inside(c, p) { return c.x >= p.x && c.y >= p.y && c.x + c.w <= p.x + p.w && c.y + c.h <= p.y + p.h; }
function area(r) { return r.w * r.h; }
function overlapArea(a, b) {
  const w = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x);
  const h = Math.min(a.y + a.h, b.y + b.h) - Math.max(a.y, b.y);
  return w > 0 && h > 0 ? w * h : 0;
}

// 要素ごとの親 group の ID({ id: 親 ID })。親は要素を内側に含む group のうち最も小さいもの。同じ大きさの group 同士は親子にしない。
// items: block / group(/ note)の {type, id, x, y, w, h}。note は group の子として扱わない(注釈は枠に属さない)。
function parentMap(items) {
  const list = (items || []).filter(Boolean);
  const groups = list.filter(g => g.type === 'group');
  const out = {};
  for (const it of list) {
    if (it.type === 'note') continue;
    let best = null;
    for (const g of groups) {
      if (g === it || g.id === it.id || !inside(it, g)) continue;
      if (it.type === 'group' && area(g) <= area(it)) continue;
      if (!best || area(g) < area(best)) best = g;
    }
    if (best) out[it.id] = best.id;
  }
  return out;
}

// 動いた量(グリッド)から、枠を越えうる辺('l' 't' 'r' 'b')
function moveSides(dx, dy) {
  const s = [];
  if (dx < 0) s.push('l'); if (dx > 0) s.push('r');
  if (dy < 0) s.push('t'); if (dy > 0) s.push('b');
  return s;
}

// リサイズハンドルの向き(n / s / e / w の組み合わせ)から、広がりうる辺
function edgeSides(edge) {
  const s = [];
  for (const [k, v] of [['w', 'l'], ['e', 'r'], ['n', 't'], ['s', 'b']]) if ((edge || '').includes(k)) s.push(v);
  return s;
}

// 親 p を、子 c が sides の辺で margin グリッド以上内側に来るまで広げた矩形(変える必要が無ければ p と同じ値)
function growToContain(p, c, sides, margin = 1) {
  let x = p.x, y = p.y, r = p.x + p.w, b = p.y + p.h;
  const all = sides || ['l', 't', 'r', 'b'];
  if (all.includes('l') && c.x - margin < x) x = Math.max(0, c.x - margin);
  if (all.includes('t') && c.y - margin < y) y = Math.max(0, c.y - margin);
  if (all.includes('r') && c.x + c.w + margin > r) r = c.x + c.w + margin;
  if (all.includes('b') && c.y + c.h + margin > b) b = c.y + c.h + margin;
  return { x, y, w: r - x, h: b - y };
}

// 操作の後、動いた要素が操作前の親の枠をまたいでいれば親を広げ、広がった親についてその親も同じようにする。
// 広がった group が、それまで重なっていなかった要素(兄弟・親の外の要素)に掛かるなら、その要素を広がった分だけ同じ向きへ
// 押し出す(group なら中身ごと。押し出した要素がさらに別の要素に掛かれば、それも押す)。広げた group が黙って兄弟を
// 子に取り込んだり、兄弟の枠をまたいだりしない。押し出した要素が親をはみ出せば、その親も広げる。
// items: 操作後の block / group の矩形。parents: 操作前の parentMap。moved: [{ id, sides }](sides は枠を越えうる辺)。
// 親の外へ出切った要素(親と重ならない)は親から出たものとして広げない。親も一緒に動いた要素は相対位置が変わらないので見ない。
// 返り値: 動いた・広がった要素の [{ type, id, x, y, w, h }](呼び出し側が本文の行の at / size に書く)。
// seeds: [{ id, from }] 操作で from から今の矩形に広がった要素(新しい group など)。その広がりで掛かる要素を先に押し出す。
function fitParents(items, parents, moved, margin = 1, seeds = []) {
  const byId = new Map((items || []).filter(Boolean).map(i => [i.id, { ...i }]));
  const movedIds = new Set((moved || []).map(m => m.id));
  const queue = (moved || []).filter(m => !movedIds.has(parents[m.id])).map(m => ({ id: m.id, sides: m.sides }));
  const changed = new Map();
  const chain = id => { const out = []; for (let p = parents[id], n = 0; p && n < 100; p = parents[p], n++) out.push(p); return out; };
  const isDesc = (id, anc) => chain(id).includes(anc);
  const shift = (q, dx, dy) => {
    for (const it of byId.values()) {
      if (it.id !== q.id && !isDesc(it.id, q.id)) continue;
      it.x = Math.max(0, it.x + dx); it.y = Math.max(0, it.y + dy);
      changed.set(it.id, it);
    }
  };
  // 矩形 from が to に広がった・動いたとき、新しく掛かる要素を押す。skip: 押さない ID(自分・中身・祖先)
  const push = (from, to, owner, depth) => {
    if (depth > 50) return;
    const d = { l: from.x - to.x, t: from.y - to.y, r: (to.x + to.w) - (from.x + from.w), b: (to.y + to.h) - (from.y + from.h) };
    const anc = new Set(chain(owner));
    // 外側の要素から見る: group を押すと中身も一緒に動くので、中身を先に押すと二重に動く
    for (const q of [...byId.values()].sort((a, b) => chain(a.id).length - chain(b.id).length)) {
      if (q.id === owner || movedIds.has(q.id) || anc.has(q.id) || isDesc(q.id, owner)) continue;
      if (overlapArea(q, from) > 0) continue;
      // 広がった向きの先にあって、その向きと直交する範囲が重なる要素だけ。元の隙間(1 グリッドまで)を保つ分だけ押す
      const hx = q.x < to.x + to.w && to.x < q.x + q.w, hy = q.y < to.y + to.h && to.y < q.y + q.h;
      const fr = from.x + from.w, fb = from.y + from.h, tr = to.x + to.w, tb = to.y + to.h;
      let dx = 0, dy = 0;
      if (d.b > 0 && hx && q.y >= fb) dy = Math.max(0, tb + Math.min(1, q.y - fb) - q.y);
      else if (d.r > 0 && hy && q.x >= fr) dx = Math.max(0, tr + Math.min(1, q.x - fr) - q.x);
      else if (d.t > 0 && hx && q.y + q.h <= from.y) dy = -Math.max(0, q.y + q.h - (to.y - Math.min(1, from.y - q.y - q.h)));
      else if (d.l > 0 && hy && q.x + q.w <= from.x) dx = -Math.max(0, q.x + q.w - (to.x - Math.min(1, from.x - q.x - q.w)));
      if (!dx && !dy) continue;
      const old = { x: q.x, y: q.y, w: q.w, h: q.h };
      shift(q, dx, dy);
      push(old, q, q.id, depth + 1);
      queue.push({ id: q.id, sides: moveSides(dx, dy) });
    }
  };
  for (const sd of seeds || []) { const it = byId.get(sd.id); if (it && sd.from) push(sd.from, it, sd.id, 0); }
  for (let guard = 0; queue.length && guard < 1000; guard++) {
    const { id, sides } = queue.shift();
    const it = byId.get(id), pid = parents[id], p = pid && byId.get(pid);
    if (!it || !p || !sides || !sides.length) continue;
    if (overlapArea(it, p) === 0) continue;
    const n = growToContain(p, it, sides, margin);
    const grew = [];
    if (n.x < p.x) grew.push('l'); if (n.y < p.y) grew.push('t');
    if (n.x + n.w > p.x + p.w) grew.push('r'); if (n.y + n.h > p.y + p.h) grew.push('b');
    if (!grew.length) continue;
    const old = { x: p.x, y: p.y, w: p.w, h: p.h };
    Object.assign(p, n);
    changed.set(pid, p);
    push(old, p, pid, 0);
    queue.push({ id: pid, sides: grew });
  }
  return [...changed.values()].map(({ type, id, x, y, w, h }) => ({ type: type || 'group', id, x, y, w, h }));
}

// 「選択をグループ化」の新しい group の矩形。選んだ要素の外接矩形に、左右下 1・上 2(ラベルの帯)の余白を付ける。
// 余白が選んでいない要素の枠をまたぐ(一部だけ重なる)なら、その辺の余白を 1、0 と詰める。親 group(parent)があれば、
// 1 を超える余白は親の内側 1 グリッドに収まる範囲に詰める(親の枠に重ねない。足りない分は fitParents で親が広がる)。
// members: 選んだ要素。others: 選んでいない block / group(親 group 自身を含めてよい。選んだ要素を内側に含む group は見ない)。
function groupRectFor(members, others, parent) {
  const ms = (members || []).filter(Boolean);
  if (!ms.length) return null;
  const minX = Math.min(...ms.map(m => m.x)), minY = Math.min(...ms.map(m => m.y));
  const maxX = Math.max(...ms.map(m => m.x + m.w)), maxY = Math.max(...ms.map(m => m.y + m.h));
  const bbox = { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
  const ids = new Set(ms.map(m => m.id));
  const obs = (others || []).filter(o => o && !ids.has(o.id) && !inside(bbox, o));
  const want = { t: 2, l: 1, r: 1, b: 1 };
  const m = { t: 0, l: 0, r: 0, b: 0 };
  const rectOf = k => {
    const x = Math.max(0, minX - k.l), y = Math.max(0, minY - k.t);
    return { x, y, w: maxX + k.r - x, h: maxY + k.b - y };
  };
  const straddles = r => obs.some(o => overlapArea(r, o) > 0 && !inside(o, r));
  const inParent = (r, side) => !parent || (side === 'l' ? r.x >= parent.x + 1 : side === 't' ? r.y >= parent.y + 1
    : side === 'r' ? r.x + r.w <= parent.x + parent.w - 1 : r.y + r.h <= parent.y + parent.h - 1);
  for (const side of ['t', 'l', 'r', 'b']) {
    for (let k = want[side]; k >= 1; k--) {
      const cand = { ...m, [side]: k }, r = rectOf(cand);
      if (straddles(r)) continue;
      if (k > 1 && !inParent(r, side)) continue;
      m[side] = k;
      break;
    }
  }
  return rectOf(m);
}

// group gr の直下の block(子 group の中の block は含まない)のうち、読み順で最後のもの。無ければ null
function lastChildBlock(items, gr) {
  const list = (items || []).filter(Boolean), parents = parentMap(list);
  const kids = list.filter(b => b.type === 'block' && parents[b.id] === gr.id);
  kids.sort((a, b) => a.y === b.y ? a.x - b.x : a.y - b.y);
  return kids.pop() || null;
}

// 「+ グループ内にブロック追加」と group 内への貼り付けの置き場所。gr の内側(左右下 1・上 2 のラベルの帯)に placeNext で並べる。
// 避けるのは gr と重なる要素すべて(子・孫・子 group の枠・gr の枠をまたぐもの)。gr を含む親は避けない。
// 返り値 { x, y, group }。group は置いた要素が収まるよう右・下に広げた gr の矩形(広げる必要が無ければ gr と同じ値)。
function placeInGroup(items, gr, w, h, prev) {
  const pad = 1, labelH = 2;
  const obs = (items || []).filter(x => x && x.id !== gr.id && overlapArea(x, gr) > 0 && !inside(gr, x));
  const p = placeNext(obs, w, h, { prev, x0: gr.x + pad, y0: gr.y + labelH, cols: gr.x + gr.w - pad });
  const group = { x: gr.x, y: gr.y, w: Math.max(gr.w, p.x + w + pad - gr.x), h: Math.max(gr.h, p.y + h + pad - gr.y) };
  return { x: p.x, y: p.y, group };
}

// placeInGroup で置き、gr が広がるなら fitParents で後始末する: 広がった gr が新しく掛かる要素(兄弟・親の外の group や block)を
// 隙間を保って押し出し(group なら中身ごと)、gr や押し出した要素が親の枠をまたげば親も広げる。「+ ブロック追加」を group 内で
// 続けても、広がった group がほかの group に重ならない。items: block / group / note(note は置き場所で避けるだけで、押さない)。
// 返り値 { x, y, changes }。changes は広がった gr を含む、動いた・広がった要素(fitParents と同じ形。呼び出し側が本文の行に書く)
function placeInGroupFit(items, gr, w, h, prev, margin = 1) {
  const list = (items || []).filter(Boolean);
  const p = placeInGroup(list, gr, w, h, prev), ng = p.group;
  if (ng.w === gr.w && ng.h === gr.h) return { x: p.x, y: p.y, changes: [] };
  const boxes = list.filter(i => i.type !== 'note');
  const parents = parentMap(boxes);
  const cur = boxes.map(i => (i.id === gr.id ? { ...i, ...ng } : i));
  const ch = fitParents(cur, parents, [{ id: gr.id, sides: ['r', 'b'] }], margin, [{ id: gr.id, from: { x: gr.x, y: gr.y, w: gr.w, h: gr.h } }]);
  const changes = [{ type: 'group', id: gr.id, x: ng.x, y: ng.y, w: ng.w, h: ng.h }, ...ch.filter(c => c.id !== gr.id)];
  return { x: p.x, y: p.y, changes };
}

;window.StableBlockLayout = { contentExtent, grownCanvasSize, setCanvasInDsl, setCanvasRouteInDsl, setCanvasGrowInDsl, canvasGrows, growCanvasInDsl, findFreeSlot, placeNext, fitZoom, stepZoom, paneWidths, parentMap, moveSides, edgeSides, growToContain, fitParents, groupRectFor, lastChildBlock, placeInGroup, placeInGroupFit };
