// Auto-generated by core/excel/build-browser.mjs from layout-core.mjs.
// DO NOT EDIT MANUALLY. Run `npm run build:browser` to regenerate.
// StableBlock キャンバスと配置の共有ロジック(HTML版 / VSCode拡張 Webview 共用)。
// browser 版は core/excel/build-browser.mjs が layout-core.browser.js を生成する
// (window.StableBlockLayout)。DOM API は使用禁止 — node --test で検証する純粋関数のみ。
//
// 座標の単位: 要素(block / group / note)の x,y,w,h はグリッド、キャンバスの width / height は px。

// 要素の右端・下端(グリッド)。要素が無ければ 0。
function contentExtent(items) {
  let right = 0, bottom = 0;
  for (const it of items || []) {
    if (!it) continue;
    right = Math.max(right, it.x + it.w);
    bottom = Math.max(bottom, it.y + it.h);
  }
  return { right, bottom };
}

// 要素が全部収まるキャンバス寸法(px)。広げるだけで縮めない。広げるときは右・下に margin グリッドの余白を残す。
function grownCanvasSize(canvas, items, margin = 1) {
  const g = canvas.grid || 20;
  const { right, bottom } = contentExtent(items);
  let width = canvas.width, height = canvas.height;
  if (right * g > width) width = (right + margin) * g;
  if (bottom * g > height) height = (bottom + margin) * g;
  return { width, height };
}

// 本文の `@canvas` 行の width / height だけを書き換える(ほかの属性・空白・改行コードは触らない)。
// `@canvas` 行が無ければ、先頭のコメント行の直後に 1 行足す。変える必要が無ければ同じ文字列を返す。
function setCanvasInDsl(dsl, width, height) {
  const eol = dsl.includes('\r\n') ? '\r\n' : '\n';
  const lines = dsl.split('\n');
  const idx = lines.findIndex(l => /^\s*@canvas(\s|$)/.test(l));
  if (idx < 0) {
    let at = 0;
    while (at < lines.length && /^\s*#/.test(lines[at])) at++;
    const line = `@canvas width=${width} height=${height}` + (eol === '\r\n' ? '\r' : '');
    lines.splice(at, 0, line);
    return lines.join('\n');
  }
  let line = lines[idx];
  const cr = line.endsWith('\r') ? '\r' : '';
  if (cr) line = line.slice(0, -1);
  for (const [key, val] of [['width', width], ['height', height]]) {
    const re = new RegExp(`(^|\\s)${key}=\\d+`);
    if (re.test(line)) line = line.replace(re, `$1${key}=${val}`);
    else line = line.replace(/\s*$/, '') + ` ${key}=${val}`;
  }
  lines[idx] = line + cr;
  const out = lines.join('\n');
  return out === dsl ? dsl : out;
}

// 要素がキャンバスからはみ出していれば `@canvas` 行を広げた本文を返す。はみ出していなければ同じ文字列。
function growCanvasInDsl(dsl, canvas, items, margin = 1) {
  const { width, height } = grownCanvasSize(canvas, items, margin);
  if (width === canvas.width && height === canvas.height) return dsl;
  return setCanvasInDsl(dsl, width, height);
}

function overlaps(a, b, gap) {
  return a.x < b.x + b.w + gap && b.x < a.x + a.w + gap && a.y < b.y + b.h + gap && b.y < a.y + a.h + gap;
}

// w x h の要素を、既存の要素と gap グリッド以上離して置ける位置を読み順(上の行から、左から)で探す。
// 横は cols(グリッド)に収まる範囲で探し、収まる所が無ければ既存の要素の下に置く。
function findFreeSlot(items, w, h, opts = {}) {
  const x0 = opts.x0 ?? 1, y0 = opts.y0 ?? 1, gap = opts.gap ?? 1;
  const list = (items || []).filter(Boolean);
  const cols = Math.max(opts.cols ?? 48, x0 + w);
  const { bottom } = contentExtent(list);
  for (let y = y0; y <= bottom + gap; y++) {
    for (let x = x0; x + w <= cols; x++) {
      const r = { x, y, w, h };
      if (!list.some(it => overlaps(r, it, gap))) return { x, y };
    }
  }
  return { x: x0, y: Math.max(y0, bottom + gap) };
}

// 「+ ブロック追加」(ツール欄・group 欄)と貼り付けの置き場所。1 つの規則で決める:
// 直前に置いたもの prev の右隣(同じ行)から読み順で、w x h を既存の要素と gap 以上離して置ける位置を探す。
// 行の右端 cols(グリッド、この値は含まない)を超えるなら次の行の x0 へ。下は足りるまで伸ばす(呼び出し側が
// キャンバスや group を広げる)。prev が無ければ領域の左上(x0, y0)から探す。
function placeNext(items, w, h, opts = {}) {
  const x0 = opts.x0 ?? 1, y0 = opts.y0 ?? 1, gap = opts.gap ?? 1, prev = opts.prev || null;
  const list = (items || []).filter(Boolean);
  const cols = Math.max(opts.cols ?? 48, x0 + w);
  const { bottom } = contentExtent(list);
  const startY = prev ? Math.max(y0, prev.y) : y0;
  const lastY = Math.max(bottom, startY) + gap;
  for (let y = startY; y <= lastY; y++) {
    const xs = prev && y === startY ? Math.max(x0, prev.x + prev.w + gap) : x0;
    for (let x = xs; x + w <= cols; x++) {
      const r = { x, y, w, h };
      if (!list.some(it => overlaps(r, it, gap))) return { x, y };
    }
  }
  return { x: x0, y: lastY };
}

// キャンバス(px)を表示欄(px)に収める倍率。max を超えて拡大しない。
function fitZoom(canvasW, canvasH, areaW, areaH, opts = {}) {
  const min = opts.min ?? 0.1, max = opts.max ?? 1;
  if (!(canvasW > 0 && canvasH > 0 && areaW > 0 && areaH > 0)) return max;
  const z = Math.min(areaW / canvasW, areaH / canvasH, max);
  return Math.max(min, Math.floor(z * 100) / 100);
}

// −/+ ボタンの次の倍率。0.25 刻みに揃える(全体表示で端数になった倍率からも刻みに戻る)。
function stepZoom(zoom, dir, opts = {}) {
  const min = opts.min ?? 0.25, max = opts.max ?? 3, step = 0.25;
  const next = dir > 0 ? Math.floor(zoom / step + 1e-9) * step + step : Math.ceil(zoom / step - 1e-9) * step - step;
  if (dir < 0) return Math.max(Math.min(min, zoom), next);
  return Math.max(min, Math.min(max, next));
}

;window.StableBlockLayout = { contentExtent, grownCanvasSize, setCanvasInDsl, growCanvasInDsl, findFreeSlot, placeNext, fitZoom, stepZoom };
